import React from 'react';
import { Link } from 'react-router-dom';
import SEOMeta from '../components/SEOMeta';
import './Commercial.css';

const criteria = [
  { title: 'A defined question set.', ask: 'Which buyers, markets and prompts will you test?', answer: 'A relevant sample, with agreed platforms and repeatable wording. Not a single screenshot presented as your entire AI visibility.' },
  { title: 'Evidence you can inspect.', ask: 'Can I see what the conclusions are based on?', answer: 'Recorded answers, dates, source links where available, and the checks where your brand is absent. Observations should be separate from interpretation.' },
  { title: 'A practical worklist.', ask: 'What changes will you actually deliver?', answer: 'Named pages, entity information, appropriate structured data and technical improvements. Clear access requirements, owners and review points.' },
  { title: 'Honest measurement.', ask: 'How will you report change without overstating it?', answer: 'Repeat the agreed sample. Explain platform variability and attribution limits. Deliverable milestones are not deadlines for AI recommendations.' },
];

export default function HireGEOAgency() {
  return <div className="cm-page">
    <SEOMeta title="Hire a GEO Agency — Who to Hire to Get Cited on ChatGPT | Qlavo" description="Hire Qlavo, a worldwide B2B GEO agency headquartered in New Delhi, for scoped AI visibility audits, implementation, and ongoing support." path="/hire-geo-agency" />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebPage', name: 'Hire a GEO Agency — Who to Hire to Get Cited on ChatGPT', url: 'https://qlavo.in/hire-geo-agency', description: 'Qlavo is a worldwide B2B GEO agency headquartered in New Delhi, offering scoped audits, implementation, and ongoing support.', isPartOf: { '@type': 'WebSite', name: 'Qlavo', url: 'https://qlavo.in' }, about: { '@id': 'https://qlavo.in#organization' } }) }} />
    <section className="q-container cm-hero">
      <p className="q-eyebrow">Hire a GEO agency / A buyer’s guide</p>
      <h1 className="q-title">Hire for the work.<br /><span className="cm-muted">Ask for the evidence.</span></h1>
      <div className="cm-hero-bottom"><p className="q-lede">If the brief is “understand and improve how AI describes our business,” look for more than a renamed content calendar. Here is what to ask a GEO agency. Including us.</p><Link className="q-button" to="/contact">Discuss your brief <span aria-hidden="true">↗</span></Link></div>
    </section>
    <section className="q-container q-section q-rule" aria-labelledby="criteria-heading"><div className="cm-section-intro"><p className="q-eyebrow">Your selection checklist</p><h2 className="q-section-heading" id="criteria-heading">Four things worth asking.</h2></div><ol className="cm-selection-list">{criteria.map((item, index) => <li key={item.title}><span className="cm-row-index">0{index + 1}</span><div><h3>{item.title}</h3><p className="cm-selection-question">{item.ask}</p></div><p className="cm-muted">{item.answer}</p></li>)}</ol></section>
    <section className="q-container q-section q-rule cm-split"><div><p className="q-eyebrow">SEO & GEO</p><h2 className="q-section-heading">Shared foundations.<br />A different lens.</h2></div><div className="cm-prose"><p>SEO works on organic search visibility, useful content and technical accessibility. GEO adds a closer look at how generated answers represent your business and which sources they reference.</p><p>They overlap. Clear pages, credible evidence and consistent entity information can support both. Neither a schema change nor a content plan buys you a place in an AI answer.</p><Link className="q-text-link" to="/ai-visibility">See how we approach AI visibility</Link></div></section>
    <section className="q-container q-section q-rule cm-split"><div><p className="q-eyebrow">Working with Qlavo</p><h2 className="q-section-heading">A defined starting point.<br />Not a placement promise.</h2><p className="cm-muted">Founded in 2025 by Ansh Bhatia. Headquartered in New Delhi. Remote B2B engagements for India, the US, UK, EU and Gulf.</p></div><div><dl className="cm-scope-inputs"><div><dt>Baseline audit</dt><dd>Record the current sample and identify priorities.</dd></div><div><dt>Implementation</dt><dd>Deliver agreed content, entity and technical changes.</dd></div><div><dt>Ongoing support</dt><dd>Repeat checks and maintain an agreed improvement backlog.</dd></div></dl><p className="cm-note">Each engagement has an agreed scope and quote. We do not guarantee rankings, AI recommendations, citation counts or results on a deadline.</p><Link className="q-text-link cm-founder-link" to="/pricing">Explore engagement details <span aria-hidden="true">↗</span></Link></div></section>
    <section className="q-container q-section q-rule cm-split"><div><p className="q-eyebrow">Working across markets</p><h2 className="q-section-heading">Headquarters is a fact.<br />Not a service limit.</h2></div><div className="cm-faq"><details><summary>Can Qlavo work with a US or UK business?</summary><p>Yes. We offer remote engagements for businesses targeting India, the US, UK, EU and Gulf. We agree markets, language requirements and responsibilities before work starts.</p></details><details><summary>Do you have a US or Dubai office?</summary><p>No. Our headquarters is New Delhi, India. Serving a market is not the same as having an office there.</p></details><details><summary>Can you work under our agency’s brand?</summary><p>Yes, through our separate <Link className="q-text-link" to="/partners">white-label partner service</Link>. Direct brand engagements and agency delivery are scoped separately.</p></details></div></section>
    <section className="q-container q-section q-rule cm-endnote"><p className="q-eyebrow">Make the brief concrete</p><h2 className="q-section-heading">What do your buyers ask?</h2><p>Bring your website, market and a question you want answered. We will discuss whether a scoped engagement is useful.</p><div className="cm-actions"><Link className="q-button" to="/contact">Book a discovery call <span aria-hidden="true">↗</span></Link><a className="q-text-link" href="mailto:info@qlavo.in">info@qlavo.in</a></div></section>
  </div>;
}
